/* eslint-disable no-console */
/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Custom Service Worker with Push Notifications Support
 *
 * This Service Worker extends the default Workbox SW generated by vite-plugin-pwa
 * to add support for Web Push notifications.
 *
 * Features:
 * - Push event handler for Web Push API
 * - Notification click handler
 * - Auto-focus or open app on notification click
 * - Custom notification actions (view, dismiss)
 */

/// <reference lib="webworker" />
import { clientsClaim } from "workbox-core";
import {
  precacheAndRoute,
  cleanupOutdatedCaches,
  matchPrecache,
} from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import {
  NetworkOnly,
  StaleWhileRevalidate,
  CacheFirst,
} from "workbox-strategies";
import { ExpirationPlugin } from "workbox-expiration";
import { BackgroundSyncPlugin } from "workbox-background-sync";

declare const self: ServiceWorkerGlobalScope;

const API_DOMAINS = ["ocpp.charge.redpay.kg"] as const;

// No-op logger to avoid direct console output in production (pre-commit hook restriction)
const swLog = (..._args: unknown[]) => {};

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cleanup outdated caches
cleanupOutdatedCaches();

// При установке нового SW — сразу активируем (skipWaiting)
// Это критично для Vercel deploys: новые JS-бандлы имеют другие хеши,
// и старый SW будет отдавать 404 на новые файлы.
// cleanupOutdatedCaches() выше уже удаляет устаревшие precache записи.
self.addEventListener("install", () => {
  self.skipWaiting();
});

/**
 * Runtime caching policies (Security Baseline)
 * injectManifest требует явной регистрации маршрутов в sw.ts
 */

// Broadcast helper
async function broadcast(type: string, payload?: Record<string, unknown>) {
  try {
    const clientList = await self.clients.matchAll({
      type: "window",
      includeUncontrolled: true,
    });
    for (const client of clientList) {
      client.postMessage({ source: "rp-sw", type, payload });
    }
  } catch {
    // ignore
  }
}

// SPA navigation fallback: любые навигации (кроме /api и статических ассетов)
// всегда отдаем precached index.html, чтобы избежать 404 от nginx при прямом заходе.
registerRoute(
  ({ request, url }) => {
    try {
      if (request.mode !== "navigate") return false;
      if (url.origin !== self.location.origin) return false;
      // Исключаем API и статику
      if (/^\/api\//i.test(url.pathname)) return false;
      if (/^\/assets\//i.test(url.pathname)) return false;
      if (
        /\.(?:ico|png|jpg|jpeg|svg|gif|webp|json|txt|woff2?|ttf|otf)$/i.test(
          url.pathname,
        )
      )
        return false;
      return true;
    } catch {
      return false;
    }
  },
  async () => {
    const index = await matchPrecache("/index.html");
    return (index as Response) || new Response("", { status: 200 });
  },
);

// Отдаем иконку, если браузер запрашивает /favicon.ico (избегаем 404)
registerRoute(
  ({ url }) =>
    url.origin === self.location.origin && url.pathname === "/favicon.ico",
  async () =>
    ((await matchPrecache(
      "/icons/manifest-icon-192.maskable.png",
    )) as Response) || new Response("", { status: 404 }),
);

// Background Sync for safe mutations (exclude auth/charging/status/payments)
const mutationBgSync = new BackgroundSyncPlugin("mutations-queue", {
  maxRetentionTime: 60 * 24, // minutes (24h)
});

registerRoute(
  ({ url, request }) => {
    try {
      if (request.method === "GET") return false;
      if (url.hostname !== self.location.hostname && !API_DOMAINS.includes(url.hostname as typeof API_DOMAINS[number])) return false;
      if (!/^\/api\//i.test(url.pathname)) return false;
      // Exclude sensitive/critical endpoints from replay
      if (/^\/api\/v1\/(charging|status|auth|payments)\//i.test(url.pathname))
        return false;
      return true;
    } catch {
      return false;
    }
  },
  new NetworkOnly({
    plugins: [mutationBgSync],
  }),
);

// Notify app when background sync kicks in
self.addEventListener("sync", (event: any) => {
  try {
    if (
      event &&
      typeof event.tag === "string" &&
      event.tag === "workbox-background-sync:mutations-queue"
    ) {
      broadcast("BG_SYNC_TRIGGER", { tag: event.tag });
    }
  } catch {
    // ignore
  }
});

// 1) Никогда не кэшировать запросы с Authorization
registerRoute(({ request }) => {
  try {
    return request.headers.has("Authorization");
  } catch {
    return false;
  }
}, new NetworkOnly());

// 2) Никогда не кэшировать Supabase (могут быть приватные ответы)
registerRoute(
  ({ url }) => /\.supabase\.co$/i.test(url.hostname),
  new NetworkOnly(),
);

// 3) OCPP критичные эндпойнты (charging/status/station) — только сеть
// ВАЖНО: station/status должен быть NetworkOnly, иначе StaleWhileRevalidate
// показывает устаревшие данные о статусе коннекторов на мобильных устройствах
registerRoute(
  ({ url }) =>
    (url.hostname === self.location.hostname || API_DOMAINS.includes(url.hostname as typeof API_DOMAINS[number])) &&
    /^\/api\/v1\/(charging|status|station)\//i.test(url.pathname),
  new NetworkOnly(),
);

// 4) Все остальные API GET — NetworkOnly (не кэшировать, ошибки обрабатывает приложение)
registerRoute(
  ({ url, request }) => {
    if (request.method !== "GET") return false;
    return (url.hostname === self.location.hostname || API_DOMAINS.includes(url.hostname as typeof API_DOMAINS[number])) && /^\/api\//i.test(url.pathname);
  },
  new NetworkOnly(),
);

// 5) JSON — SWR
registerRoute(
  ({ url }) => url.pathname.endsWith(".json"),
  new StaleWhileRevalidate({
    cacheName: "json-swr",
  }),
);

// 6) Шрифты — SWR
registerRoute(
  ({ url }) => /\.(woff2?|ttf|otf)$/i.test(url.pathname),
  new StaleWhileRevalidate({
    cacheName: "fonts-swr",
  }),
);

// 7) Изображения — CacheFirst с TTL
registerRoute(
  ({ url }) => /\.(png|jpg|jpeg|svg|gif|webp)$/i.test(url.pathname),
  new CacheFirst({
    cacheName: "images-cache",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 дней
      }),
    ],
  }),
);

/**
 * Activate Event Handler
 *
 * For first-time installations, take control immediately.
 * For updates, wait for user confirmation.
 */
self.addEventListener("activate", (event) => {
  swLog("[SW] Activate event");

  // Only claim clients on first installation (no previous controller)
  event.waitUntil(
    self.clients.matchAll({ type: "window" }).then((clients) => {
      const hasController = clients.some(
        (client) =>
          client.url && new URL(client.url).origin === self.location.origin,
      );

      if (!hasController) {
        // First installation - take control immediately
        swLog("[SW] First installation - claiming clients");
        return clientsClaim();
      }

      // Update - wait for user confirmation (SKIP_WAITING message)
      swLog("[SW] Update detected - waiting for user confirmation");
      return Promise.resolve();
    }),
  );
});

/**
 * Push Event Handler
 *
 * Backend v1.3.0: Handles push notifications from /api/v1/notifications
 * Triggered when a push notification is received from the server.
 * Displays a notification to the user.
 *
 * Notification types:
 * - Client: charging_started, charging_completed, charging_error, low_balance_warning, payment_confirmed
 * - Owner: new_session, session_completed, station_offline
 */
self.addEventListener("push", (event: PushEvent) => {
  swLog("[SW] Push event received:", event);

  if (!event.data) {
    console.warn("[SW] Push event has no data");
    return;
  }

  let notificationOptions: NotificationOptions & { vibrate?: number[] } = {
    icon: "/icons/manifest-icon-192.maskable.png",
    badge: "/icons/manifest-icon-192.maskable.png",
    vibrate: [200, 100, 200],
    requireInteraction: false,
    tag: "rp-notification",
  };

  let title = "Red Petroleum";
  let payload: any;

  // Parse push payload (Backend v1.3.0 sends JSON)
  try {
    payload = event.data.json();
    swLog("[SW] Push payload:", payload);

    // Extract notification properties from payload
    title = payload.title || title;
    notificationOptions = {
      ...notificationOptions,
      body: payload.body,
      icon: payload.icon || notificationOptions.icon,
      badge: payload.badge || notificationOptions.badge,
      data: payload.data || {},
      requireInteraction: payload.requireInteraction || false,
      tag: payload.tag || payload.data?.type || "rp-notification",
    } as NotificationOptions & { vibrate?: number[] };
  } catch (error) {
    console.error("[SW] Failed to parse push payload:", error);
    // Fallback to text
    notificationOptions.body = event.data.text();
  }

  // Show notification
  const promiseChain = self.registration.showNotification(
    title,
    notificationOptions,
  );

  event.waitUntil(promiseChain);
});

/**
 * Notification Click Handler
 *
 * Backend v1.3.0: Routes notification clicks based on notification type
 * Triggered when user clicks on a notification.
 * Opens the app or focuses existing window and navigates to relevant page.
 *
 * Routing:
 * - charging_started/completed/error -> /sessions/{session_id}
 * - low_balance_warning -> /balance/topup
 * - payment_confirmed -> /balance
 * - new_session/session_completed (owner) -> /owner/sessions/{session_id}
 * - station_offline (owner) -> /owner/stations/{station_id}
 */
self.addEventListener("notificationclick", (event: NotificationEvent) => {
  swLog("[SW] Notification click:", event.action, event.notification.data);

  // Close notification
  event.notification.close();

  // Handle notification actions
  if (event.action === "dismiss") {
    return; // Just close the notification
  }

  const notificationData = event.notification.data;
  let url = "/";

  // Route based on notification type (Backend v1.3.0 spec)
  if (notificationData && notificationData.type) {
    switch (notificationData.type) {
      // Client notifications
      case "charging_started":
      case "charging_completed":
      case "charging_error":
        url = notificationData.session_id
          ? `/sessions/${notificationData.session_id}`
          : "/user/history";
        break;

      case "low_balance_warning":
        url = event.action === "topup" ? "/topup" : "/user/history";
        break;

      case "payment_confirmed":
        url = "/balance";
        break;

      // Owner notifications
      case "new_session":
      case "session_completed":
        url = notificationData.session_id
          ? `/owner/sessions/${notificationData.session_id}`
          : "/owner/dashboard";
        break;

      case "station_offline":
        url = notificationData.station_id
          ? `/owner/stations/${notificationData.station_id}`
          : "/owner/stations";
        break;

      default:
        // Use URL from notification data if provided
        url = notificationData.url || "/";
    }
  } else {
    // Fallback to URL in notification data
    url = notificationData?.url || "/";
  }

  swLog("[SW] Navigating to:", url);

  // Open or focus app window
  const promiseChain = self.clients
    .matchAll({
      type: "window",
      includeUncontrolled: true,
    })
    .then((clientList) => {
      // Try to find existing window
      for (const client of clientList) {
        if ("focus" in client) {
          // Navigate to URL and focus
          client.navigate(url);
          return client.focus();
        }
      }

      // No existing window, open new one
      if (self.clients.openWindow) {
        return self.clients.openWindow(url);
      }

      return undefined;
    });

  event.waitUntil(promiseChain);
});

/**
 * Push Subscription Change Handler
 *
 * Backend v1.3.0: Auto-cleanup handled by backend on 410/404
 * Triggered when push subscription changes (e.g., user revokes permission).
 *
 * Note: Backend automatically removes invalid subscriptions when push fails with 410/404.
 * Users should re-subscribe manually through the app UI.
 */
self.addEventListener("pushsubscriptionchange", (event: Event) => {
  swLog("[SW] Push subscription changed:", event);
  console.warn(
    "[SW] Push subscription expired. Please re-subscribe through app settings.",
  );

  // Log event for debugging (backend handles cleanup automatically)
  // User needs to re-subscribe manually through the app UI
});

/**
 * Message Handler
 *
 * Handle messages from the main app (e.g., to show notifications from app).
 */
self.addEventListener("message", (event: ExtendableMessageEvent) => {
  swLog("[SW] Message received:", event.data);

  if (event.data && event.data.type === "SHOW_NOTIFICATION") {
    const { title, options } = event.data;

    self.registration.showNotification(title, {
      icon: "/icons/manifest-icon-192.maskable.png",
      badge: "/icons/manifest-icon-192.maskable.png",
      vibrate: [200, 100, 200],
      ...options,
    });
  }

  // Standard vite-plugin-pwa message handling
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

swLog("[SW] Service Worker loaded with Push Notifications support");
